#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Handyman.Resource", IsApplication=true)]

namespace Handyman
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int sliding_Right = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int sliding_Up = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int barStyle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int buttonStyle = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070009
			public const int btSign = 2131165193;
			
			// aapt resource value: 0x7f070005
			public const int btSignUp = 2131165189;
			
			// aapt resource value: 0x7f07000b
			public const int btlogin = 2131165195;
			
			// aapt resource value: 0x7f07000d
			public const int btregister = 2131165197;
			
			// aapt resource value: 0x7f070004
			public const int etRegEmail = 2131165188;
			
			// aapt resource value: 0x7f070000
			public const int etRegName = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int etRegPassword = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int etRegSurname = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int etRegUsername = 2131165186;
			
			// aapt resource value: 0x7f070007
			public const int etpassword = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int etusername = 2131165190;
			
			// aapt resource value: 0x7f07000f
			public const int progressBar1 = 2131165199;
			
			// aapt resource value: 0x7f07000e
			public const int rtLayout = 2131165198;
			
			// aapt resource value: 0x7f07000a
			public const int tvHeader = 2131165194;
			
			// aapt resource value: 0x7f07000c
			public const int tvOr = 2131165196;
			
			// aapt resource value: 0x7f070008
			public const int tvforgotpassword = 2131165192;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int DialogActivity = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int LoginActivity = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int dialog_animation = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
